//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointAuction.ControlTemplates.SharePointAuction {
    
    
    public partial class Home {
        
        /// <summary>
        /// AuctionTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal AuctionTitle;
        
        /// <summary>
        /// LeftHandNav1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharePointAuction.ControlTemplates.SharePointAuction.LeftHandNav LeftHandNav1;
        
        /// <summary>
        /// ItemGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SharePointAuction.ControlTemplates.SharePointAuction.ItemGrid ItemGrid1;
    }
}
